/**
 *
 *  Chunk.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Chunk.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::Soplon;

const std::string Chunk::Cols::_id = "id";
const std::string Chunk::Cols::_id_file = "id_file";
const std::string Chunk::Cols::_lineBegin = "lineBegin";
const std::string Chunk::Cols::_lineEnd = "lineEnd";
const std::string Chunk::Cols::_buffer = "buffer";
const std::string Chunk::Cols::_author = "author";
const std::string Chunk::primaryKeyName = "id";
const bool Chunk::hasPrimaryKey = true;
const std::string Chunk::tableName = "chunk";

const std::vector<typename Chunk::MetaData> Chunk::metaData_={
{"id","int32_t","int(11)",4,1,1,1},
{"id_file","int32_t","int(11)",4,0,0,1},
{"lineBegin","int32_t","int(11)",4,0,0,0},
{"lineEnd","int32_t","int(11)",4,0,0,0},
{"buffer","std::string","varchar(100)",100,0,0,0},
{"author","int32_t","int(11)",4,0,0,0}
};
const std::string &Chunk::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Chunk::Chunk(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["id_file"].isNull())
        {
            idFile_=std::make_shared<int32_t>(r["id_file"].as<int32_t>());
        }
        if(!r["lineBegin"].isNull())
        {
            linebegin_=std::make_shared<int32_t>(r["lineBegin"].as<int32_t>());
        }
        if(!r["lineEnd"].isNull())
        {
            lineend_=std::make_shared<int32_t>(r["lineEnd"].as<int32_t>());
        }
        if(!r["buffer"].isNull())
        {
            buffer_=std::make_shared<std::string>(r["buffer"].as<std::string>());
        }
        if(!r["author"].isNull())
        {
            author_=std::make_shared<int32_t>(r["author"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            idFile_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            linebegin_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            lineend_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            buffer_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            author_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Chunk::Chunk(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            idFile_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            linebegin_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            lineend_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            buffer_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            author_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
}

Chunk::Chunk(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("id_file"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["id_file"].isNull())
        {
            idFile_=std::make_shared<int32_t>((int32_t)pJson["id_file"].asInt64());
        }
    }
    if(pJson.isMember("lineBegin"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["lineBegin"].isNull())
        {
            linebegin_=std::make_shared<int32_t>((int32_t)pJson["lineBegin"].asInt64());
        }
    }
    if(pJson.isMember("lineEnd"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["lineEnd"].isNull())
        {
            lineend_=std::make_shared<int32_t>((int32_t)pJson["lineEnd"].asInt64());
        }
    }
    if(pJson.isMember("buffer"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["buffer"].isNull())
        {
            buffer_=std::make_shared<std::string>(pJson["buffer"].asString());
        }
    }
    if(pJson.isMember("author"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["author"].isNull())
        {
            author_=std::make_shared<int32_t>((int32_t)pJson["author"].asInt64());
        }
    }
}

void Chunk::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            idFile_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            linebegin_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            lineend_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            buffer_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            author_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
}

void Chunk::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("id_file"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["id_file"].isNull())
        {
            idFile_=std::make_shared<int32_t>((int32_t)pJson["id_file"].asInt64());
        }
    }
    if(pJson.isMember("lineBegin"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["lineBegin"].isNull())
        {
            linebegin_=std::make_shared<int32_t>((int32_t)pJson["lineBegin"].asInt64());
        }
    }
    if(pJson.isMember("lineEnd"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["lineEnd"].isNull())
        {
            lineend_=std::make_shared<int32_t>((int32_t)pJson["lineEnd"].asInt64());
        }
    }
    if(pJson.isMember("buffer"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["buffer"].isNull())
        {
            buffer_=std::make_shared<std::string>(pJson["buffer"].asString());
        }
    }
    if(pJson.isMember("author"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["author"].isNull())
        {
            author_=std::make_shared<int32_t>((int32_t)pJson["author"].asInt64());
        }
    }
}

const int32_t &Chunk::getValueOfId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Chunk::getId() const noexcept
{
    return id_;
}
void Chunk::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Chunk::PrimaryKeyType & Chunk::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int32_t &Chunk::getValueOfIdFile() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(idFile_)
        return *idFile_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Chunk::getIdFile() const noexcept
{
    return idFile_;
}
void Chunk::setIdFile(const int32_t &pIdFile) noexcept
{
    idFile_ = std::make_shared<int32_t>(pIdFile);
    dirtyFlag_[1] = true;
}

const int32_t &Chunk::getValueOfLinebegin() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(linebegin_)
        return *linebegin_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Chunk::getLinebegin() const noexcept
{
    return linebegin_;
}
void Chunk::setLinebegin(const int32_t &pLinebegin) noexcept
{
    linebegin_ = std::make_shared<int32_t>(pLinebegin);
    dirtyFlag_[2] = true;
}
void Chunk::setLinebeginToNull() noexcept
{
    linebegin_.reset();
    dirtyFlag_[2] = true;
}

const int32_t &Chunk::getValueOfLineend() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(lineend_)
        return *lineend_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Chunk::getLineend() const noexcept
{
    return lineend_;
}
void Chunk::setLineend(const int32_t &pLineend) noexcept
{
    lineend_ = std::make_shared<int32_t>(pLineend);
    dirtyFlag_[3] = true;
}
void Chunk::setLineendToNull() noexcept
{
    lineend_.reset();
    dirtyFlag_[3] = true;
}

const std::string &Chunk::getValueOfBuffer() const noexcept
{
    const static std::string defaultValue = std::string();
    if(buffer_)
        return *buffer_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Chunk::getBuffer() const noexcept
{
    return buffer_;
}
void Chunk::setBuffer(const std::string &pBuffer) noexcept
{
    buffer_ = std::make_shared<std::string>(pBuffer);
    dirtyFlag_[4] = true;
}
void Chunk::setBuffer(std::string &&pBuffer) noexcept
{
    buffer_ = std::make_shared<std::string>(std::move(pBuffer));
    dirtyFlag_[4] = true;
}
void Chunk::setBufferToNull() noexcept
{
    buffer_.reset();
    dirtyFlag_[4] = true;
}

const int32_t &Chunk::getValueOfAuthor() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(author_)
        return *author_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Chunk::getAuthor() const noexcept
{
    return author_;
}
void Chunk::setAuthor(const int32_t &pAuthor) noexcept
{
    author_ = std::make_shared<int32_t>(pAuthor);
    dirtyFlag_[5] = true;
}
void Chunk::setAuthorToNull() noexcept
{
    author_.reset();
    dirtyFlag_[5] = true;
}

void Chunk::updateId(const uint64_t id)
{
    id_ = std::make_shared<int32_t>(static_cast<int32_t>(id));
}

const std::vector<std::string> &Chunk::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id_file",
        "lineBegin",
        "lineEnd",
        "buffer",
        "author"
    };
    return inCols;
}

void Chunk::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getIdFile())
        {
            binder << getValueOfIdFile();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getLinebegin())
        {
            binder << getValueOfLinebegin();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getLineend())
        {
            binder << getValueOfLineend();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getBuffer())
        {
            binder << getValueOfBuffer();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getAuthor())
        {
            binder << getValueOfAuthor();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Chunk::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void Chunk::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getIdFile())
        {
            binder << getValueOfIdFile();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getLinebegin())
        {
            binder << getValueOfLinebegin();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getLineend())
        {
            binder << getValueOfLineend();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getBuffer())
        {
            binder << getValueOfBuffer();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getAuthor())
        {
            binder << getValueOfAuthor();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Chunk::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getIdFile())
    {
        ret["id_file"]=getValueOfIdFile();
    }
    else
    {
        ret["id_file"]=Json::Value();
    }
    if(getLinebegin())
    {
        ret["lineBegin"]=getValueOfLinebegin();
    }
    else
    {
        ret["lineBegin"]=Json::Value();
    }
    if(getLineend())
    {
        ret["lineEnd"]=getValueOfLineend();
    }
    else
    {
        ret["lineEnd"]=Json::Value();
    }
    if(getBuffer())
    {
        ret["buffer"]=getValueOfBuffer();
    }
    else
    {
        ret["buffer"]=Json::Value();
    }
    if(getAuthor())
    {
        ret["author"]=getValueOfAuthor();
    }
    else
    {
        ret["author"]=Json::Value();
    }
    return ret;
}

Json::Value Chunk::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getIdFile())
            {
                ret[pMasqueradingVector[1]]=getValueOfIdFile();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getLinebegin())
            {
                ret[pMasqueradingVector[2]]=getValueOfLinebegin();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getLineend())
            {
                ret[pMasqueradingVector[3]]=getValueOfLineend();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getBuffer())
            {
                ret[pMasqueradingVector[4]]=getValueOfBuffer();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getAuthor())
            {
                ret[pMasqueradingVector[5]]=getValueOfAuthor();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getIdFile())
    {
        ret["id_file"]=getValueOfIdFile();
    }
    else
    {
        ret["id_file"]=Json::Value();
    }
    if(getLinebegin())
    {
        ret["lineBegin"]=getValueOfLinebegin();
    }
    else
    {
        ret["lineBegin"]=Json::Value();
    }
    if(getLineend())
    {
        ret["lineEnd"]=getValueOfLineend();
    }
    else
    {
        ret["lineEnd"]=Json::Value();
    }
    if(getBuffer())
    {
        ret["buffer"]=getValueOfBuffer();
    }
    else
    {
        ret["buffer"]=Json::Value();
    }
    if(getAuthor())
    {
        ret["author"]=getValueOfAuthor();
    }
    else
    {
        ret["author"]=Json::Value();
    }
    return ret;
}

bool Chunk::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("id_file"))
    {
        if(!validJsonOfField(1, "id_file", pJson["id_file"], err, true))
            return false;
    }
    else
    {
        err="The id_file column cannot be null";
        return false;
    }
    if(pJson.isMember("lineBegin"))
    {
        if(!validJsonOfField(2, "lineBegin", pJson["lineBegin"], err, true))
            return false;
    }
    if(pJson.isMember("lineEnd"))
    {
        if(!validJsonOfField(3, "lineEnd", pJson["lineEnd"], err, true))
            return false;
    }
    if(pJson.isMember("buffer"))
    {
        if(!validJsonOfField(4, "buffer", pJson["buffer"], err, true))
            return false;
    }
    if(pJson.isMember("author"))
    {
        if(!validJsonOfField(5, "author", pJson["author"], err, true))
            return false;
    }
    return true;
}
bool Chunk::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Chunk::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("id_file"))
    {
        if(!validJsonOfField(1, "id_file", pJson["id_file"], err, false))
            return false;
    }
    if(pJson.isMember("lineBegin"))
    {
        if(!validJsonOfField(2, "lineBegin", pJson["lineBegin"], err, false))
            return false;
    }
    if(pJson.isMember("lineEnd"))
    {
        if(!validJsonOfField(3, "lineEnd", pJson["lineEnd"], err, false))
            return false;
    }
    if(pJson.isMember("buffer"))
    {
        if(!validJsonOfField(4, "buffer", pJson["buffer"], err, false))
            return false;
    }
    if(pJson.isMember("author"))
    {
        if(!validJsonOfField(5, "author", pJson["author"], err, false))
            return false;
    }
    return true;
}
bool Chunk::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Chunk::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }

            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
