/**
 *
 *  Denominationlinkedgroup.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Denominationlinkedgroup.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::Soplon;

const std::string Denominationlinkedgroup::Cols::_id = "id";
const std::string Denominationlinkedgroup::Cols::_id_denom = "id_denom";
const std::string Denominationlinkedgroup::Cols::_id_group = "id_group";
const std::string Denominationlinkedgroup::Cols::_occ = "occ";
const std::string Denominationlinkedgroup::primaryKeyName = "id";
const bool Denominationlinkedgroup::hasPrimaryKey = true;
const std::string Denominationlinkedgroup::tableName = "denominationlinkedgroup";

const std::vector<typename Denominationlinkedgroup::MetaData> Denominationlinkedgroup::metaData_={
{"id","int32_t","int(11)",4,1,1,1},
{"id_denom","int32_t","int(11)",4,0,0,1},
{"id_group","int32_t","int(11)",4,0,0,1},
{"occ","int32_t","int(11)",4,0,0,1}
};
const std::string &Denominationlinkedgroup::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Denominationlinkedgroup::Denominationlinkedgroup(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["id_denom"].isNull())
        {
            idDenom_=std::make_shared<int32_t>(r["id_denom"].as<int32_t>());
        }
        if(!r["id_group"].isNull())
        {
            idGroup_=std::make_shared<int32_t>(r["id_group"].as<int32_t>());
        }
        if(!r["occ"].isNull())
        {
            occ_=std::make_shared<int32_t>(r["occ"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            idDenom_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            idGroup_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            occ_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Denominationlinkedgroup::Denominationlinkedgroup(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            idDenom_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            idGroup_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            occ_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
}

Denominationlinkedgroup::Denominationlinkedgroup(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("id_denom"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["id_denom"].isNull())
        {
            idDenom_=std::make_shared<int32_t>((int32_t)pJson["id_denom"].asInt64());
        }
    }
    if(pJson.isMember("id_group"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["id_group"].isNull())
        {
            idGroup_=std::make_shared<int32_t>((int32_t)pJson["id_group"].asInt64());
        }
    }
    if(pJson.isMember("occ"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["occ"].isNull())
        {
            occ_=std::make_shared<int32_t>((int32_t)pJson["occ"].asInt64());
        }
    }
}

void Denominationlinkedgroup::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            idDenom_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            idGroup_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            occ_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
}

void Denominationlinkedgroup::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("id_denom"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["id_denom"].isNull())
        {
            idDenom_=std::make_shared<int32_t>((int32_t)pJson["id_denom"].asInt64());
        }
    }
    if(pJson.isMember("id_group"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["id_group"].isNull())
        {
            idGroup_=std::make_shared<int32_t>((int32_t)pJson["id_group"].asInt64());
        }
    }
    if(pJson.isMember("occ"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["occ"].isNull())
        {
            occ_=std::make_shared<int32_t>((int32_t)pJson["occ"].asInt64());
        }
    }
}

const int32_t &Denominationlinkedgroup::getValueOfId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Denominationlinkedgroup::getId() const noexcept
{
    return id_;
}
void Denominationlinkedgroup::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Denominationlinkedgroup::PrimaryKeyType & Denominationlinkedgroup::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int32_t &Denominationlinkedgroup::getValueOfIdDenom() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(idDenom_)
        return *idDenom_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Denominationlinkedgroup::getIdDenom() const noexcept
{
    return idDenom_;
}
void Denominationlinkedgroup::setIdDenom(const int32_t &pIdDenom) noexcept
{
    idDenom_ = std::make_shared<int32_t>(pIdDenom);
    dirtyFlag_[1] = true;
}

const int32_t &Denominationlinkedgroup::getValueOfIdGroup() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(idGroup_)
        return *idGroup_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Denominationlinkedgroup::getIdGroup() const noexcept
{
    return idGroup_;
}
void Denominationlinkedgroup::setIdGroup(const int32_t &pIdGroup) noexcept
{
    idGroup_ = std::make_shared<int32_t>(pIdGroup);
    dirtyFlag_[2] = true;
}

const int32_t &Denominationlinkedgroup::getValueOfOcc() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(occ_)
        return *occ_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Denominationlinkedgroup::getOcc() const noexcept
{
    return occ_;
}
void Denominationlinkedgroup::setOcc(const int32_t &pOcc) noexcept
{
    occ_ = std::make_shared<int32_t>(pOcc);
    dirtyFlag_[3] = true;
}

void Denominationlinkedgroup::updateId(const uint64_t id)
{
    id_ = std::make_shared<int32_t>(static_cast<int32_t>(id));
}

const std::vector<std::string> &Denominationlinkedgroup::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id_denom",
        "id_group",
        "occ"
    };
    return inCols;
}

void Denominationlinkedgroup::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getIdDenom())
        {
            binder << getValueOfIdDenom();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getIdGroup())
        {
            binder << getValueOfIdGroup();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getOcc())
        {
            binder << getValueOfOcc();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Denominationlinkedgroup::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void Denominationlinkedgroup::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getIdDenom())
        {
            binder << getValueOfIdDenom();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getIdGroup())
        {
            binder << getValueOfIdGroup();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getOcc())
        {
            binder << getValueOfOcc();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Denominationlinkedgroup::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getIdDenom())
    {
        ret["id_denom"]=getValueOfIdDenom();
    }
    else
    {
        ret["id_denom"]=Json::Value();
    }
    if(getIdGroup())
    {
        ret["id_group"]=getValueOfIdGroup();
    }
    else
    {
        ret["id_group"]=Json::Value();
    }
    if(getOcc())
    {
        ret["occ"]=getValueOfOcc();
    }
    else
    {
        ret["occ"]=Json::Value();
    }
    return ret;
}

Json::Value Denominationlinkedgroup::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getIdDenom())
            {
                ret[pMasqueradingVector[1]]=getValueOfIdDenom();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getIdGroup())
            {
                ret[pMasqueradingVector[2]]=getValueOfIdGroup();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getOcc())
            {
                ret[pMasqueradingVector[3]]=getValueOfOcc();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getIdDenom())
    {
        ret["id_denom"]=getValueOfIdDenom();
    }
    else
    {
        ret["id_denom"]=Json::Value();
    }
    if(getIdGroup())
    {
        ret["id_group"]=getValueOfIdGroup();
    }
    else
    {
        ret["id_group"]=Json::Value();
    }
    if(getOcc())
    {
        ret["occ"]=getValueOfOcc();
    }
    else
    {
        ret["occ"]=Json::Value();
    }
    return ret;
}

bool Denominationlinkedgroup::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("id_denom"))
    {
        if(!validJsonOfField(1, "id_denom", pJson["id_denom"], err, true))
            return false;
    }
    else
    {
        err="The id_denom column cannot be null";
        return false;
    }
    if(pJson.isMember("id_group"))
    {
        if(!validJsonOfField(2, "id_group", pJson["id_group"], err, true))
            return false;
    }
    else
    {
        err="The id_group column cannot be null";
        return false;
    }
    if(pJson.isMember("occ"))
    {
        if(!validJsonOfField(3, "occ", pJson["occ"], err, true))
            return false;
    }
    else
    {
        err="The occ column cannot be null";
        return false;
    }
    return true;
}
bool Denominationlinkedgroup::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                                 const std::vector<std::string> &pMasqueradingVector,
                                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Denominationlinkedgroup::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("id_denom"))
    {
        if(!validJsonOfField(1, "id_denom", pJson["id_denom"], err, false))
            return false;
    }
    if(pJson.isMember("id_group"))
    {
        if(!validJsonOfField(2, "id_group", pJson["id_group"], err, false))
            return false;
    }
    if(pJson.isMember("occ"))
    {
        if(!validJsonOfField(3, "occ", pJson["occ"], err, false))
            return false;
    }
    return true;
}
bool Denominationlinkedgroup::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                               const std::vector<std::string> &pMasqueradingVector,
                                                               std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Denominationlinkedgroup::validJsonOfField(size_t index,
                                               const std::string &fieldName,
                                               const Json::Value &pJson,
                                               std::string &err,
                                               bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
