/**
 *
 *  File.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "File.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::Soplon;

const std::string File::Cols::_id = "id";
const std::string File::Cols::_nom = "nom";
const std::string File::Cols::_nb_lignes = "nb_lignes";
const std::string File::primaryKeyName = "id";
const bool File::hasPrimaryKey = true;
const std::string File::tableName = "file";

const std::vector<typename File::MetaData> File::metaData_={
{"id","int32_t","int(11)",4,0,1,1},
{"nom","std::string","varchar(100)",100,0,0,0},
{"nb_lignes","int32_t","int(11)",4,0,0,0}
};
const std::string &File::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
File::File(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["nom"].isNull())
        {
            nom_=std::make_shared<std::string>(r["nom"].as<std::string>());
        }
        if(!r["nb_lignes"].isNull())
        {
            nbLignes_=std::make_shared<int32_t>(r["nb_lignes"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            nom_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            nbLignes_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

File::File(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            nom_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            nbLignes_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

File::File(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("nom"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["nom"].isNull())
        {
            nom_=std::make_shared<std::string>(pJson["nom"].asString());
        }
    }
    if(pJson.isMember("nb_lignes"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["nb_lignes"].isNull())
        {
            nbLignes_=std::make_shared<int32_t>((int32_t)pJson["nb_lignes"].asInt64());
        }
    }
}

void File::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            nom_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            nbLignes_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

void File::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("nom"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["nom"].isNull())
        {
            nom_=std::make_shared<std::string>(pJson["nom"].asString());
        }
    }
    if(pJson.isMember("nb_lignes"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["nb_lignes"].isNull())
        {
            nbLignes_=std::make_shared<int32_t>((int32_t)pJson["nb_lignes"].asInt64());
        }
    }
}

const int32_t &File::getValueOfId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &File::getId() const noexcept
{
    return id_;
}
void File::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename File::PrimaryKeyType & File::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &File::getValueOfNom() const noexcept
{
    const static std::string defaultValue = std::string();
    if(nom_)
        return *nom_;
    return defaultValue;
}
const std::shared_ptr<std::string> &File::getNom() const noexcept
{
    return nom_;
}
void File::setNom(const std::string &pNom) noexcept
{
    nom_ = std::make_shared<std::string>(pNom);
    dirtyFlag_[1] = true;
}
void File::setNom(std::string &&pNom) noexcept
{
    nom_ = std::make_shared<std::string>(std::move(pNom));
    dirtyFlag_[1] = true;
}
void File::setNomToNull() noexcept
{
    nom_.reset();
    dirtyFlag_[1] = true;
}

const int32_t &File::getValueOfNbLignes() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(nbLignes_)
        return *nbLignes_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &File::getNbLignes() const noexcept
{
    return nbLignes_;
}
void File::setNbLignes(const int32_t &pNbLignes) noexcept
{
    nbLignes_ = std::make_shared<int32_t>(pNbLignes);
    dirtyFlag_[2] = true;
}
void File::setNbLignesToNull() noexcept
{
    nbLignes_.reset();
    dirtyFlag_[2] = true;
}

void File::updateId(const uint64_t id)
{
}

const std::vector<std::string> &File::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "nom",
        "nb_lignes"
    };
    return inCols;
}

void File::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getNom())
        {
            binder << getValueOfNom();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getNbLignes())
        {
            binder << getValueOfNbLignes();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> File::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void File::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getNom())
        {
            binder << getValueOfNom();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getNbLignes())
        {
            binder << getValueOfNbLignes();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value File::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getNom())
    {
        ret["nom"]=getValueOfNom();
    }
    else
    {
        ret["nom"]=Json::Value();
    }
    if(getNbLignes())
    {
        ret["nb_lignes"]=getValueOfNbLignes();
    }
    else
    {
        ret["nb_lignes"]=Json::Value();
    }
    return ret;
}

Json::Value File::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getNom())
            {
                ret[pMasqueradingVector[1]]=getValueOfNom();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getNbLignes())
            {
                ret[pMasqueradingVector[2]]=getValueOfNbLignes();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getNom())
    {
        ret["nom"]=getValueOfNom();
    }
    else
    {
        ret["nom"]=Json::Value();
    }
    if(getNbLignes())
    {
        ret["nb_lignes"]=getValueOfNbLignes();
    }
    else
    {
        ret["nb_lignes"]=Json::Value();
    }
    return ret;
}

bool File::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    else
    {
        err="The id column cannot be null";
        return false;
    }
    if(pJson.isMember("nom"))
    {
        if(!validJsonOfField(1, "nom", pJson["nom"], err, true))
            return false;
    }
    if(pJson.isMember("nb_lignes"))
    {
        if(!validJsonOfField(2, "nb_lignes", pJson["nb_lignes"], err, true))
            return false;
    }
    return true;
}
bool File::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                              const std::vector<std::string> &pMasqueradingVector,
                                              std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool File::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("nom"))
    {
        if(!validJsonOfField(1, "nom", pJson["nom"], err, false))
            return false;
    }
    if(pJson.isMember("nb_lignes"))
    {
        if(!validJsonOfField(2, "nb_lignes", pJson["nb_lignes"], err, false))
            return false;
    }
    return true;
}
bool File::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector,
                                            std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool File::validJsonOfField(size_t index,
                            const std::string &fieldName,
                            const Json::Value &pJson,
                            std::string &err,
                            bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
