/**
 *
 *  Groupcomposition.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Groupcomposition.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::Soplon;

const std::string Groupcomposition::Cols::_id = "id";
const std::string Groupcomposition::Cols::_id_group = "id_group";
const std::string Groupcomposition::Cols::_id_author = "id_author";
const std::string Groupcomposition::primaryKeyName = "id";
const bool Groupcomposition::hasPrimaryKey = true;
const std::string Groupcomposition::tableName = "groupcomposition";

const std::vector<typename Groupcomposition::MetaData> Groupcomposition::metaData_={
{"id","int32_t","int(11)",4,1,1,1},
{"id_group","int32_t","int(11)",4,0,0,1},
{"id_author","int32_t","int(11)",4,0,0,1}
};
const std::string &Groupcomposition::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Groupcomposition::Groupcomposition(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["id_group"].isNull())
        {
            idGroup_=std::make_shared<int32_t>(r["id_group"].as<int32_t>());
        }
        if(!r["id_author"].isNull())
        {
            idAuthor_=std::make_shared<int32_t>(r["id_author"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            idGroup_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            idAuthor_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Groupcomposition::Groupcomposition(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            idGroup_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            idAuthor_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

Groupcomposition::Groupcomposition(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("id_group"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["id_group"].isNull())
        {
            idGroup_=std::make_shared<int32_t>((int32_t)pJson["id_group"].asInt64());
        }
    }
    if(pJson.isMember("id_author"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["id_author"].isNull())
        {
            idAuthor_=std::make_shared<int32_t>((int32_t)pJson["id_author"].asInt64());
        }
    }
}

void Groupcomposition::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            idGroup_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            idAuthor_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

void Groupcomposition::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("id_group"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["id_group"].isNull())
        {
            idGroup_=std::make_shared<int32_t>((int32_t)pJson["id_group"].asInt64());
        }
    }
    if(pJson.isMember("id_author"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["id_author"].isNull())
        {
            idAuthor_=std::make_shared<int32_t>((int32_t)pJson["id_author"].asInt64());
        }
    }
}

const int32_t &Groupcomposition::getValueOfId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Groupcomposition::getId() const noexcept
{
    return id_;
}
void Groupcomposition::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Groupcomposition::PrimaryKeyType & Groupcomposition::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int32_t &Groupcomposition::getValueOfIdGroup() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(idGroup_)
        return *idGroup_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Groupcomposition::getIdGroup() const noexcept
{
    return idGroup_;
}
void Groupcomposition::setIdGroup(const int32_t &pIdGroup) noexcept
{
    idGroup_ = std::make_shared<int32_t>(pIdGroup);
    dirtyFlag_[1] = true;
}

const int32_t &Groupcomposition::getValueOfIdAuthor() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(idAuthor_)
        return *idAuthor_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Groupcomposition::getIdAuthor() const noexcept
{
    return idAuthor_;
}
void Groupcomposition::setIdAuthor(const int32_t &pIdAuthor) noexcept
{
    idAuthor_ = std::make_shared<int32_t>(pIdAuthor);
    dirtyFlag_[2] = true;
}

void Groupcomposition::updateId(const uint64_t id)
{
    id_ = std::make_shared<int32_t>(static_cast<int32_t>(id));
}

const std::vector<std::string> &Groupcomposition::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id_group",
        "id_author"
    };
    return inCols;
}

void Groupcomposition::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getIdGroup())
        {
            binder << getValueOfIdGroup();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getIdAuthor())
        {
            binder << getValueOfIdAuthor();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Groupcomposition::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void Groupcomposition::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getIdGroup())
        {
            binder << getValueOfIdGroup();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getIdAuthor())
        {
            binder << getValueOfIdAuthor();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Groupcomposition::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getIdGroup())
    {
        ret["id_group"]=getValueOfIdGroup();
    }
    else
    {
        ret["id_group"]=Json::Value();
    }
    if(getIdAuthor())
    {
        ret["id_author"]=getValueOfIdAuthor();
    }
    else
    {
        ret["id_author"]=Json::Value();
    }
    return ret;
}

Json::Value Groupcomposition::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getIdGroup())
            {
                ret[pMasqueradingVector[1]]=getValueOfIdGroup();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getIdAuthor())
            {
                ret[pMasqueradingVector[2]]=getValueOfIdAuthor();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getIdGroup())
    {
        ret["id_group"]=getValueOfIdGroup();
    }
    else
    {
        ret["id_group"]=Json::Value();
    }
    if(getIdAuthor())
    {
        ret["id_author"]=getValueOfIdAuthor();
    }
    else
    {
        ret["id_author"]=Json::Value();
    }
    return ret;
}

bool Groupcomposition::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("id_group"))
    {
        if(!validJsonOfField(1, "id_group", pJson["id_group"], err, true))
            return false;
    }
    else
    {
        err="The id_group column cannot be null";
        return false;
    }
    if(pJson.isMember("id_author"))
    {
        if(!validJsonOfField(2, "id_author", pJson["id_author"], err, true))
            return false;
    }
    else
    {
        err="The id_author column cannot be null";
        return false;
    }
    return true;
}
bool Groupcomposition::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                          const std::vector<std::string> &pMasqueradingVector,
                                                          std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Groupcomposition::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("id_group"))
    {
        if(!validJsonOfField(1, "id_group", pJson["id_group"], err, false))
            return false;
    }
    if(pJson.isMember("id_author"))
    {
        if(!validJsonOfField(2, "id_author", pJson["id_author"], err, false))
            return false;
    }
    return true;
}
bool Groupcomposition::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Groupcomposition::validJsonOfField(size_t index,
                                        const std::string &fieldName,
                                        const Json::Value &pJson,
                                        std::string &err,
                                        bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
